# Generated by Django 5.2.1 on 2025-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cash_currency",
            field=models.CharField(default="USD", max_length=150),
        ),
    ]
