# Generated by Django 5.2.1 on 2025-06-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_cash_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cash_currency",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
