# Generated by Django 5.2.1 on 2025-05-27 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="name",
        ),
    ]
