# Generated by Django 5.2.1 on 2025-05-27 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_remove_expense_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="name",
        ),
    ]
