# Generated by Django 5.2.1 on 2025-05-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_remove_income_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.expensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.incomecategory",
            ),
        ),
        migrations.AlterField(
            model_name="incomecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
