# Generated by Django 5.2.1 on 2025-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_alter_expense_category_alter_expensecategory_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(max_length=200),
        ),
    ]
