# Generated by Django 5.2.1 on 2025-05-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_alter_expense_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.CharField(max_length=200),
        ),
    ]
