# Generated by Django 5.2.1 on 2025-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_remove_expensecategory_user_remove_income_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="expense_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
